# Generated by Django 5.2.8 on 2025-11-20 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL),
        ),
    ]
