# Generated by Django 5.2.5 on 2025-09-02 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='perfil_linkedin',
            new_name='perfil_likendin',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='competencias',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='planopago',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratafacil.usuario'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='competencias',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
