# Generated by Django 5.2.5 on 2025-09-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0002_rename_perfil_linkedin_candidato_perfil_likendin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='perfil_likendin',
            new_name='perfil_linkedin',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='competencias',
        ),
        migrations.AddField(
            model_name='candidato',
            name='competencias',
            field=models.ManyToManyField(blank=True, to='contratafacil.competencia'),
        ),
    ]
