# Generated by Django 5.2.8 on 2025-11-21 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0002_candidato_id_alter_candidato_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='id',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidato', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
