# Generated by Django 5.2.7 on 2025-10-28 13:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0003_rename_perfil_likendin_candidato_perfil_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='contratafacil.usuario'),
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='avaliacoesla',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='estrutura',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='texto',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='curriculos',
            field=models.FileField(null=True, upload_to='curriculos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
