# Generated by Django 5.2.8 on 2025-11-23 14:26

import contratafacil.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0003_remove_candidato_id_alter_candidato_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='curriculoNome',
            field=models.CharField(blank=True, null=True, verbose_name='Nome de arquivo do currículo'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='curriculo',
            field=models.FileField(null=True, upload_to=contratafacil.models.RenomearDoc('curriculos/'), validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Arquivo de currículo'),
        ),
    ]
