# Generated by Django 5.2.8 on 2025-11-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0004_curriculo_curriculonome_alter_curriculo_curriculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculo',
            old_name='curriculoNome',
            new_name='arquivoNome',
        ),
    ]
