# Generated by Django 5.2.7 on 2025-11-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0005_delete_competencia_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('candidato', 'Candidato'), ('Empresa', 'empresa')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
