# Generated by Django 5.2.8 on 2025-11-24 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0005_rename_curriculonome_curriculo_arquivonome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculo',
            old_name='arquivoNome',
            new_name='arquivo_nome',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratafacil.empresa'),
        ),
    ]
