# Generated by Django 5.2.7 on 2025-11-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0006_alter_usuario_tipo_de_usuario_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa')], null=True),
        ),
    ]
