# Generated by Django 5.2.7 on 2025-11-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0007_alter_usuario_senha_alter_usuario_tipo_de_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('candidato', 'Candidato'), ('Empresa', 'empresa')], null=True),
        ),
    ]
