# Generated by Django 5.2.7 on 2025-11-03 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0009_alter_usuario_tipo_de_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
    ]
