# Generated by Django 5.2.7 on 2025-11-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0010_rename_senha_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=500, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('Candidato', 'candidato'), ('empresa', 'Empresa')], null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nome'),
        ),
    ]
