# Generated by Django 5.2.7 on 2025-11-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0011_alter_usuario_password_alter_usuario_tipo_de_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('candidato', 'Candidato'), ('Empresa', 'empresa')], null=True),
        ),
    ]
