# Generated by Django 5.2.7 on 2025-11-06 21:51

import contratafacil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0012_alter_usuario_tipo_de_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='plano_pago',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_de_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=contratafacil.models.RenomearImagem('ftPerfil/')),
        ),
    ]
