# Generated by Django 5.2.8 on 2025-11-10 16:14

import contratafacil.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0013_remove_usuario_plano_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='curriculos',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='curriculo',
            field=models.FileField(null=True, upload_to=contratafacil.models.RenomearArquivoTexto('curriculos/'), validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plano_pago',
            field=models.BooleanField(default=False),
        ),
    ]
