# Generated by Django 5.2.7 on 2025-11-15 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0014_remove_curriculo_curriculos_curriculo_curriculo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telephone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_pago', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curriculo',
            name='candidato',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Currículos', to='contratafacil.candidato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='contratafacil.candidato'),
        ),
    ]
