# Generated by Django 5.2.7 on 2025-11-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0015_rename_telephone_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratafacil.empresa'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contratafacil.empresa'),
            preserve_default=False,
        ),
    ]
