# Generated by Django 5.2.7 on 2025-11-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0016_usuario_empresa_vaga_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Salário'),
            preserve_default=False,
        ),
    ]
