# Generated by Django 5.2.8 on 2025-11-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratafacil', '0019_alter_vaga_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
